### PR TITLE
prevent removing errors messages by duping original models error messages to failed instances

### LINKED ISSUE #331: not possible to read errors messages since 0.14.0 on failed instances
Hello, 
method `import_with_validations( column_names, array_of_attributes, options = {} )`

related commit  https://github.com/zdennis/activerecord-import/commit/d0322abe5d40c69fd89672f56e32bfa10fc8c150

before this commit implementation returned validated models

```
 failed_instances << instance
```
after
```
 failed_instances << model.dup
```
This makes it impossible to read error messages 
Example

```
model.errors.full_messages
=> ["Last name has already been taken"]

model.dup.errors.full_messages
=> []
```

### PR DESCRIPTION
**Pull request by Fivell**
fixes #331

### CODE REVIEW

File: lib/activerecord-import/import.rb [hunk 1]
```diff
@@ -476,7 +476,7 @@ def import_with_validations( column_names, array_of_attributes, options = {} )
           next if model.valid?(options[:validate_with_context])
           raise(ActiveRecord::RecordInvalid, model) if options[:raise_error]
           array_of_attributes[i] = nil
-          failed_instances << model.dup
```
Comment (jkowens) [inline lib/activerecord-import/import.rb]: The reason the model is duped is because it is being reused to validate attribute values instead of instantiating a new instance for every record. I think it might be possible to dupe the errors as well.

Can you try something like:
```
failure = model.dup
failure.errors.send(:initialize_dup, model.errors)
```

**Comment by jkowens** [comment]
Thanks for reporting this issue, it definitely needs fixed!

File: lib/activerecord-import/import.rb (hunk 1 above)
Comment (jkowens) [inline lib/activerecord-import/import.rb]: See https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L473. The variable `model` is instantiated outside of the loop so it is being reused to save the time of repeatedly instantiating a new one.

If you don't dupe it, `failed_instances` will be an array of the same object.

Comment (Fivell) [inline lib/activerecord-import/import.rb]: >>Can you try something like:

done

**Comment by jkowens** [comment]
Sorry, one last thing, could you amend the commit message?

**Comment by Fivell** [comment]
@jkowens , sure

**Comment by jkowens** [comment]
Thanks again!

**Comment by Fivell** [comment]
@jkowens , you're welcome!
BTW any thoughts time of release? I need it to close another issue in dependent project :)

**Comment by jkowens** [comment]
This was just released in v0.16.1 🚀
