### PR TITLE
Fix issues running tests for AR 4.0 and 4.1

### LINKED ISSUE #211: Serialization fails when serializing to JSON
activerecord-import supports saving serialized fields, as described in this spec:

```ruby
  describe "importing serialized fields" do
    it "imports values for serialized fields" do
      assert_difference "Widget.unscoped.count", +1 do
        Widget.import [:w_id, :data], [[1, {:a => :b}]]
      end
      assert_equal({:a => :b}, Widget.find_by_w_id(1).data)
    end
  end
```

However, this fails when `serialize :data, JSON` is used instead of `serialize :data, Hash`. Instead of serializing to JSON, the data is serialized to YAML (the ActiveRecord default). This can be reproduced by changing the `serialize` line in `widget.rb` to `serialize :data, JSON`, as demonstrated [in this branch](https://github.com/zdennis/activerecord-import/compare/master...MaxGabriel:serializeJSON?expand=1).

### PR DESCRIPTION
**Pull request by jkowens**
Tests were only running for latest AR 4.2 because the version specifier wasn't to the patch level.

Once tests were running an issue with :synchronize showed up for AR 4.0 and 4.1. This PR incorporates the fix in #176.

Also found that tests for serialization weren't running and JSON serialization was failing on AR < 4.2. Fixes #211.

### CODE REVIEW

**Comment by jkowens** [comment]
@zdennis @sferik either of you guys have an idea why the build fails for AR 4.0 with Ruby 2.2.4? The tests run fine with Ruby 2.1, but something about 2.2 doesn't work.

**Comment by jkowens** [comment]
Well, I got the tests passing on Travis :smile: 

For some reason they still fail with Ruby 2.2.4 and AR_VERSION 4.0 on my local system...not sure why.

```
$ AR_VERSION=4.0 bundle exec rake test:postgresql
/Users/jordan/.rvm/gems/ruby-2.2.4/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require': cannot load such file -- minitest/unit (LoadError)
	from /Users/jordan/.rvm/gems/ruby-2.2.4/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `block in require'
	from /Users/jordan/.rvm/gems/ruby-2.2.4/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /Users/jordan/.rvm/gems/ruby-2.2.4/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
	from /Users/jordan/.rvm/gems/ruby-2.2.4/gems/activesupport-4.0.13/lib/active_support/test_case.rb:2:in `<top (required)>'
	from /Users/jordan/.rvm/gems/ruby-2.2.4/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
	from /Users/jordan/.rvm/gems/ruby-2.2.4/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `block in require'
	from /Users/jordan/.rvm/gems/ruby-2.2.4/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /Users/jordan/.rvm/gems/ruby-2.2.4/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
	from /Users/jordan/projects/activerecord-import/test/test_helper.rb:17:in `<top (required)>'
	from /Users/jordan/projects/activerecord-import/test/import_test.rb:1:in `require'
	from /Users/jordan/projects/activerecord-import/test/import_test.rb:1:in `<top (required)>'
	from /Users/jordan/.rvm/gems/ruby-2.2.4/gems/rake-11.1.1/lib/rake/rake_test_loader.rb:15:in `require'
	from /Users/jordan/.rvm/gems/ruby-2.2.4/gems/rake-11.1.1/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /Users/jordan/.rvm/gems/ruby-2.2.4/gems/rake-11.1.1/lib/rake/rake_test_loader.rb:4:in `select'
	from /Users/jordan/.rvm/gems/ruby-2.2.4/gems/rake-11.1.1/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
```

File: test/support/active_support/test_case_extensions.rb [hunk 1]
```diff
@@ -4,7 +4,7 @@ class ActiveSupport::TestCase
 
   class << self
     def requires_active_record_version(version_string, &blk)
-      return unless Gem::Dependency.new("expected", version_string).match?("actual", ActiveRecord::VERSION::STRING)
```
Comment (jkowens) [inline test/support/active_support/test_case_extensions.rb]: This would always return false.
